### ISSUE TITLE
Detect additio

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/physical-address-annotator-example#11]
The tool currently detects Country and ZIP code. In order to address all the location PHI defined by HIPAA, we want the tool to support the following address type:

LOCATION-CITY
LOCATION-LOCATION-OTHER
LOCATION-STATE
LOCATION-STREET
LOCATION-ZIP

These codes are the one used in the i2b2 dataset. We use different code (see nlp-sandbox-schemas).

**Comment by gkowalski** [comment]
I'm not sure I understand ? You want me to update the enumiration of types we currently have defined as : 

    PhysicalAddressAnnotation:
      type: object
      description: A physical address annotation in a text
      allOf:
        - $ref: '#/components/schemas/Annotation'
        - type: object
          properties:
            type:
              description: Type of address information
              type: string
              enum:
                - City
                - Country
                - Department
                - Hospital
                - Organization
                - Other
                - Room
                - State
                - Street
                - Zip

To these types defined by the 2014 i2b2 challange ? Or put in example code to use the existing types ( with the addition of "Location Other" ?

**Comment by tschaffter** [comment]
> To these types defined by the 2014 i2b2 challange ?
No. The existing enum is based on the definition of the i2b2 dataset and is consistent with our naming convention.

> Or put in example code to use the existing types ( with the addition of "Location Other" ?

Currently the method is only looking for country and zip. The task is to also detect City, State, Street and other.

**Comment by gkowalski** [comment]
done

**Comment by gkowalski** [comment]
The ideas placed in https://github.com/Sage-Bionetworks/nlp-sandbox-physical-address-annotator-example/pull/12 need to be  articulated  in a proper Use case before we can proceed with coding. Finalize Inputs, Outputs , algorithms to be used internally and how to handle any possible exceptions during the process.

**Comment by tschaffter** [comment]
The information in #12 should be sufficient to proceed with the implementation. If you need anything from me let me know. I'm quite busy with the many other components of the platform so if you can take the lead here, that would be great.
